import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Dashboard from "@/components/side-bar";
import { TooltipProvider } from "@/components/ui/tooltip";
import SideBar from "@/components/side-bar";
import { ChatProvider } from "@/context/chat";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider>
          <ChatProvider>
            <div className="grid h-screen w-full pl-[56px]">
              <SideBar />
              {children}
            </div>
          </ChatProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
